[workspace]
members = [
    "crates/sql-sink",
    "crates/fluvio-model-sql",
    "crates/integration-tests",
]
resolver = "2"

[profile.release-lto]
inherits = "release"
lto = true

[workspace.dependencies]
fluvio = { git = "https://github.com/infinyon/fluvio.git", tag = "v0.10.10" }
fluvio-connector-common = { git = "https://github.com/infinyon/fluvio.git", tag = "v0.10.10-dev-1" }
