[workspace]
members = [
    "crates/sql-sink",
    "crates/fluvio-model-sql",
    "crates/integration-tests",
    "crates/json-sql",
]
resolver = "2"

[profile.release-lto]
inherits = "release"
lto = true

[workspace.dependencies]
fluvio-future = "0.6.2"

fluvio = { git = "https://github.com/infinyon/fluvio", tag = "v0.11.8" }
fluvio-connector-common = { git = "https://github.com/infinyon/fluvio", tag = "v0.11.8" }
fluvio-smartmodule = { git = "https://github.com/infinyon/fluvio", tag = "v0.11.8" }
