[workspace]
members = [
    "crates/sql-sink",
    "crates/fluvio-model-sql",
    "crates/integration-tests",
    "crates/json-sql",
]
resolver = "2"

[profile.release-lto]
inherits = "release"
lto = true

[workspace.dependencies]
fluvio = { git = "https://github.com/EstebanBorai/fluvio.git", rev = "92771981594df8b75a8eca0a321ec93cc47d492d" }
fluvio-connector-common = { git = "https://github.com/EstebanBorai/fluvio.git", rev = "92771981594df8b75a8eca0a321ec93cc47d492d" }
