meta:
  name: test-postgres-with-json-sql-transformations
  type: sql-sink
  version: latest
  topic: test-postgres-with-json-sql-transformations
  create-topic: true
sql:
  url: "postgresql://pguser:passpass@127.0.0.1:5432/pguser"
transforms:
  - uses: infinyon/json-sql@0.1.0
    with:
      mapping:
        table: "test_postgres_with_json_sql_transformations"
        map-columns:
          "device_id":
            json-key: "device.device_id"
            value:
              type: "int"
              default: "0"
              required: true
          "record":
            json-key: "$"
            value:
              type: "jsonb"
              required: true
