meta:
  version: latest
  name: my-sql-connector
  type: sql-sink
  topic: sql-topic
  create-topic: true
sql:
  url: 'postgresql://myusername:mypassword@127.0.0.1:5432/postgres'
transforms:
  - uses: infinyon/json-sql@0.1.0
    invoke: insert
    with:
      mapping:
        table: "topic_message"
        map-columns:
          "device_id":
            json-key: "payload.device.device_id"
            value:
              type: "int"
              default: "0"
              required: true
          "record":
            json-key: "$"
            value:
              type: "jsonb"
              required: true
